service: rag-example-app-rag-handler


provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  stage: ${opt:stage, "dev"}
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 6

plugins:
  - serverless-python-requirements

custom:
  topicName: rag-example
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
  include:
    - "rag.py"
  exclude:
    - "requirements.txt"
    - "package.json"
    - "package-lock.json"
    - ".serverless/**"
    - ".virtualenv/**"
    - "node_modules/**"

functions:
  rag:
    handler: rag.handler
    environment:
      STAGE: ${self:provider.stage}
      PINECONE_API_KEY: ${param:PINECONE_API_KEY}
      PINECONE_ENV: ${param:PINECONE_ENV}
      OPENAI_API_KEY: ${param:OPENAI_API_KEY}
    events:
      - sns: arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.topicName}
